### PR TITLE
ISSUE-223: Allow `py/initialize!` settings to be read from a `python.edn` file

### PR DESCRIPTION
**Pull request by jjtolton**
Potentially closes: https://github.com/clj-python/libpython-clj/issues/223

### CODE REVIEW

**Comment by cnuernber** [comment]
This looks great.  simple and effective - I think it needs documentation.

**Comment by jjtolton** [comment]
Great point.  I couldn't remember why we didn't autocast these.  This is probably the reason.

**Comment by jjtolton** [comment]
Agreed.  Do you think we can merge this so I can update the clj-python template and refer to it in documentation?

**Comment by cnuernber** [comment]
I want some docs added for ‘initialize’

**Comment by cnuernber** [comment]
* docs for initialize!
* Add entry to CHANGELOG.md

**Pull request merged**
